image: registry.gitlab.ics.muni.cz:443/europdx/ci-images/docker-extended:latest

services:
  - docker:dind

before_script:
#  - apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
  - docker version
  - docker-compose version

build-proxy-master:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd proxy
    - docker build --pull -t "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
  only:
    - master

build-proxy-other:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd proxy
    - docker build --pull -t "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
  only:
    - beta
    - dev


test-build-master:
  stage: test
  script:
    #    - mkdir -p proxy/ssl
    #    - touch proxy/ssl/server.key
    #    - touch proxy/ssl/server.crt
    - docker-compose build
  only:
    - master
