image: docker:latest

services:
- docker:dind

before_script:
- apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
- docker version
- docker-compose version

test-build-master:
  stage: test
  script:
  - touch ssl/server.key
  - touch ssl/server.crt
  - docker-compose build
only:
  - master