image: registry.gitlab.ics.muni.cz:443/europdx/ci-images/docker-extended:latest

services:
  - docker:dind

before_script:
#  - apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
  - docker version
  - docker-compose version

build-proxy-master:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - sed -ie "s|\(HOST=\).*|\1$DEPLOY_TARGET|" .env
    - cd proxy
    - docker build --pull -t "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA" -t "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG"
  only:
    - master

build-proxy-beta:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - sed -ie "s|\(HOST=\).*|\1$DEPLOY_TARGET_BETA|" .env
    - cd proxy
    - docker build --pull -t "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA" -t "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG"
  only:
    - beta

build-proxy-dev:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - sed -ie "s|\(HOST=\).*|\1$DEPLOY_TARGET_DEV|" .env
    - cd proxy
    - docker build --pull -t "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA" -t "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG"
  only:
    - dev

restart-master:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -o StrictHostKeyChecking=no $DEPLOY_TARGET "cd dataportal-docker && docker-compose down && docker-compose up -d"
  only:
    - master
  when: manual

restart-beta:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -o StrictHostKeyChecking=no $DEPLOY_TARGET_BETA "cd dataportal-docker && docker-compose down && docker-compose up -d"
  only:
    - beta
  when: manual

restart-dev:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -o StrictHostKeyChecking=no $DEPLOY_TARGET_DEV "cd dataportal-docker && docker-compose down && docker-compose up -d"
  only:
    - dev
  when: manual

deploy-master:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -o StrictHostKeyChecking=no $DEPLOY_TARGET "cd dataportal-docker; git pull; docker-compose pull; docker-compose up -d"
  environment:
    name: master
    url: $DEPLOY_TARGET
  only:
    - master

deploy-beta:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -o StrictHostKeyChecking=no $DEPLOY_TARGET_BETA "cd dataportal-docker; git pull; docker-compose pull; docker-compose up -d"
  environment:
    name: beta
    url: $DEPLOY_TARGET_BETA
  only:
    - beta

deploy-dev:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -o StrictHostKeyChecking=no $DEPLOY_TARGET_DEV "cd dataportal-docker; git pull; docker-compose pull; docker-compose up -d"
  environment:
    name: dev
    url: $DEPLOY_TARGET_DEV
  only:
    - dev


test-build-master:
  stage: test
  script:
    #    - mkdir -p proxy/ssl
    #    - touch proxy/ssl/server.key
    #    - touch proxy/ssl/server.crt
    - docker-compose build
  only:
    - master
