version: '3'

services:
  web:
    container_name: pdxfinder
    restart: always
    env_file:
      - .env
    build: ./pdxfinder/
    ports:
      - 80:8080
      - 8081:8081
    links:
      - neo4j:neo4j
    volumes:
      - ./import-data:/import-data
  neo4j:
    image: neo4j:3.2
    restart: always
    container_name: neo4j
    env_file:
     - .env
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neodata:/data/
      - ./neo4j-data:/neo4j-data
volumes:
  neodata:
