version: '3'

services:
  web:
    container_name: dataportal
    restart: always
    env_file:
      - .env
    image: registry.gitlab.ics.muni.cz:443/europdx/dataportal/dataportal-sourcecode:$CI_COMMIT_REF_NAME

    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./import-data:/import-data
  neo4j:
    image: neo4j:3.2
    restart: always
    container_name: neo4j
    env_file:
     - .env
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neodata:/data/
      - ./neo4j-data:/neo4j-data
  proxy:
    container_name: proxy
    restart: always
    env_file:
      - .env
#    build:
#      context: ./proxy
    image: registry.gitlab.ics.muni.cz:443/europdx/dataportal/dataportal-docker/proxy:$CI_COMMIT_REF_NAME
    volumes:
      - ./proxy/ssl:/etc/apache2/ssl
    ports:
     - "80:80"
     - "443:443"

volumes:
  neodata:
